### ISSUE TITLE
multi-gpu support

### ISSUE THREAD

**Issue by hlsafin** [ZiyuanMa/R2D2#3]
I know that at its current state, it's only utilizing GPU for the learner and cpus for actors. Is it possible for each actor to also use GPU when feeding input to the network? How about if you have several GPU in a single node, can multiple-gpu for a speed up ? Any suggestions would be helpful.

**Comment by luo-huan-123** [comment]
As a beginner in reinforcement learning, how should I debug this multi-process and multi-thread project? In this way, I can understand R2D2 better and make certain modifications. Thanks for your help!
